// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpCUDi3c3iiSbumy457ULNQthRj2gNrxM',
    appId: '1:177241393017:web:00e0ae58ac38819e1311a8',
    messagingSenderId: '177241393017',
    projectId: 'besocial-e99b1',
    authDomain: 'besocial-e99b1.firebaseapp.com',
    storageBucket: 'besocial-e99b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0OntOS41Irstqp7SM6xLC1RAdWClo4Ec',
    appId: '1:177241393017:android:a7c13058b30fc2841311a8',
    messagingSenderId: '177241393017',
    projectId: 'besocial-e99b1',
    storageBucket: 'besocial-e99b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkttQrhOO4YHClpzBqdHlZM9TvJDSmtq0',
    appId: '1:177241393017:ios:8715a0d9fc8aa3b11311a8',
    messagingSenderId: '177241393017',
    projectId: 'besocial-e99b1',
    storageBucket: 'besocial-e99b1.appspot.com',
    iosBundleId: 'com.example.beSocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkttQrhOO4YHClpzBqdHlZM9TvJDSmtq0',
    appId: '1:177241393017:ios:8715a0d9fc8aa3b11311a8',
    messagingSenderId: '177241393017',
    projectId: 'besocial-e99b1',
    storageBucket: 'besocial-e99b1.appspot.com',
    iosBundleId: 'com.example.beSocial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpCUDi3c3iiSbumy457ULNQthRj2gNrxM',
    appId: '1:177241393017:web:f5b7e19bb80606d01311a8',
    messagingSenderId: '177241393017',
    projectId: 'besocial-e99b1',
    authDomain: 'besocial-e99b1.firebaseapp.com',
    storageBucket: 'besocial-e99b1.appspot.com',
  );

}